# Generated by Django 4.2.2 on 2023-06-25 19:34

from django.db import migrations, models
import files.models
import functools


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=functools.partial(
                            files.models._update_filename, *(), **{"path": "files"}
                        )
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
